name: "infinitas"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'infinitas_dwh'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

snapshots:
  +target_database: "{{ target.name ~ '_raw_history' if target.name in ['prod', 'acc', 'dev'] else target.database }}"
  infinitas:
    netsuite:
      +strategy: timestamp
      +target_schema: netsuite_fivetran
    salesforce:
      +strategy: timestamp
      +target_schema: salesforce_fivetran

models:
  infinitas:
    mart:
      +schema: mart
    warehouse:
      +schema: warehouse

seeds:
  infinitas:
    +schema: seed
    +quote_columns: false


vars:
  dbt_utils_dispatch_list:
    - infinitas
