trigger:
  branches:
    include:
    - master

schedules:
- cron: "0 2 * * *"
  displayName: constant build at 2:00 am every day of the week
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: Use Python 3.8

- task: DownloadSecureFile@1
  name: SettingProfile
  displayName: 'Downloading Profile for Snowflake'
  inputs:
    secureFile: 'azure_pipeline_dbt_profile.yml'

- script: |
    echo Installing $(SettingProfile.secureFilePath) to the ~/.dbt...
    mkdir ~/.dbt
    cp $(SettingProfile.secureFilePath) ~/.dbt/profiles.yml
  displayName: Installing Profile for Snowflake

- script: |
    pip install --user poetry
    echo '##vso[task.prependpath]$(HOME)/.local/bin'
  displayName: Installing poetry

- script: |
    make install
  displayName: Installing dbt and dependencies

- script: |
    make lint
  displayName: Linting project

- script: |
    DBT_PASSWORD='$(dbt_dev_password)' make seed target=dev
  displayName: Writing seed data

- script: |
    DBT_PASSWORD='$(dbt_dev_password)' make snapshot target=dev
  displayName: Taking a snapshot of landing tables

- script: |
    DBT_PASSWORD='$(dbt_dev_password)' make run target=dev
  displayName: Building models
